<?php
/**
 * Codilar_Irp extension
 * NOTICE OF LICENSE
 *
 *
 * @category  Codilar
 * @package   Codilar_Afbt
 * @copyright Copyright (c) 2019
 */

/** @var $block \Codilar\Afbt\Block\AfbtHandler */
?>

<?php if ($block->isEnabled()): ?>
    <div class="irp-container">
        <div class="loader-block">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "irpHandler": {
                    "irpFetchUrl": "<?php echo $block->getFetchUrl() ?>",
                    "product_id": "<?php echo $block->getProduct()->getId() ?>"
                }
            }
        }
    </script>
<?php endif; ?>

<style>
    .related-block-container .block-container{
        width: 100%;
    }
</style>